version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user/app1
hooks:
  BeforeInstall:
  - location: cleanup.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: fix_privileges.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: start_server.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: stop_server.sh
    timeout: 300
    runas: root